#ifndef GAME_STATE_H_HEADER_INCLUDED_A21B957C
#define GAME_STATE_H_HEADER_INCLUDED_A21B957C

class GAME_STATE
{
  public:
    GAME_STATE();

    GAME_START;
    GAME_RUN;
    GAME_PAUSE;
    GAME_UPGRADE;
    GAME_WIN;
    GAME_OVER;
    GAME_HELP;
    GAME_ABOUT;
    GAME_SETTING;
};



#endif /* GAME_STATE_H_HEADER_INCLUDED_A21B957C */
