#ifndef TRANSFER_H_HEADER_INCLUDED_A21BCA23
#define TRANSFER_H_HEADER_INCLUDED_A21BCA23

class TRANSFER
{
  public:
    TRANSFER();

    TRANS_NONE;
    TRANS_NOFLIP_ROT90;
    TRANS_NOFLIP_ROT180;
    TRANS_NOFLIP_ROT270;
    TRANS_VFLIP_NOROT;
    TRANS_VFLIP_ROT90;
    TRANS_VFLIP_ROT180;
    TRANS_VFLIP_ROT270;
    TRANS_HFLIP_NOROT;
    TRANS_HFLIP_ROT90;
    TRANS_HFLIP_ROT180;
    TRANS_HFLIP_ROT270;
};



#endif /* TRANSFER_H_HEADER_INCLUDED_A21BCA23 */
