#ifndef LAYER_TYPE_H_HEADER_INCLUDED_A21BCA09
#define LAYER_TYPE_H_HEADER_INCLUDED_A21BCA09

class LAYER_TYPE
{
  public:
    LAYER_TYPE();

    LAYER_NOTE;
    LAYER_MAP_BACK;
    LAYER_EXPLOSION;
    LAYER_BONUS;
    LAYER_NONE;
};



#endif /* LAYER_TYPE_H_HEADER_INCLUDED_A21BCA09 */
